# Generated by Django 3.2.5 on 2021-07-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210723_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publics',
            options={'verbose_name': 'Публикации', 'verbose_name_plural': 'Публикация'},
        ),
    ]
