# Generated by Django 3.2.5 on 2021-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_publics_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusNavbars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Главная'), (1, 'Публикации'), (2, 'Сообщение'), (3, 'Контакты')], default=0)),
            ],
        ),
    ]
