# Generated by Django 3.2.5 on 2021-07-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='publics',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Не нравится'),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
